baseURL: 'https://dino-s26.github.io'
languageCode: 'en-us'
title: 'Dino-s26'
pagination:
  pagerSize: "5"

theme: "PaperMod"

enableRobotsTXT: false
buildDrafts: true
buildFuture: true
buildExpired: false

enableEmoji: true

minify:
  minifyOutput: true
  disableXML: true

menu:
  main:
  - identifier: about
    name: About Me
    url: /about/
    weight: 10
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 20
  - idenfitier: archives
    name: Archives
    url: /archives/
    weight: 30
  - identifier: search
    name: Search
    url: /search/
    weight: 40

outputs:
  home:
  - HTML
  - RSS
  - JSON

params:
  env: production
  assets:
    disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
  defaultTheme: dark
  disableThemeToggle: false
  ShowPostNavLinks: true
  ShowShareButtons: true
  mainSections:
  - posts
  homeInfoParams:
    Title: Hellow, and welcome
    Content: "I'm Dino, a Tech entusiast, like to learn new tech and write posts to be share as knowledge ... [more](about)"

  socialIcons:
  - name: "Linkedin"
    url: "https://www.linkedin.com/in/alldino-syaman-5b1799109/"
  - name: "Instagram"
    url: "https://www.instagram.com/dino_s26/"
  - name: "Github"
    url: "https://github.com/Dino-s26"

  cover:
    hidden: true
    hiddenInList: true
    hiddhenInSingle: true
    shouldSort: true

  # fuseOpts:
  #  isCaseSensitive: false
  #  shouldSort: true
  #  location: 0
  #  distance: 1000
  #  threshold: 0.4
  #  minMatchCharLength: 0
  #  useExtendedSearch: true
  #  keys: ["title","permalink","summary","content"]

  staticDir:
  - static
